import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    signInWithGoogle: "Sign in with Google",
    serverNotResponding: "Server is not responding. Please try again later.",
    errorSendingPasswordResetEmail:
      "Error while sending email for password reset. Please try again later.",
    linkSentToEmail: "A link for resetting your password has been sent to your email",
    requestPasswordResetEmail: "Request a link to reset your password",
    email: "Email",
    send: "Send",
    password: "Password",
    signIn: "Sign in",
    signUp: "Sign up",
    forgotPassword: "Forgot password? Request reset here",
    accountCreationFailed: "Account creation failed",
    emailAlreadyInUse: "Email is already in use",
    invalidEmail: "Invalid email address",
    passwordTooWeak: "Password is too weak. Must be atleast 6 characters.",
    emailPasswordAccountsAreNotEnabled: "Email & Password accounts are not enabled",
    appTitle: "Easy to use timesheets and trip logging",
    infoText1: "Register for a free 30 day trial",
    infoText2: "Only 29.90 €/year after trial!",
    startFreeTrial: "Start free trial",
    timesheets: "Timesheets",
    timesheetInfo1:
      "Keep track of your work for multiple project flexibly on any device with a browser.",
    timesheetInfo2: "Use quick selection times for inputting frequently used working times",
    timesheetInfo3: "Add daily allowance and break durations.",
    timesheetInfo4:
      "Track your working time precisely with a single button click at the start and end of your working day.",
    triplogs: "Trip logs",
    triplogInfo1:
      "Keep track of your trips - quick and easy way to input your vehicle's kilometerage.",
    tripLogInfo2: "Add trips quickly by inputting kilometerage at the start and end of your trip.",
    tripLogInfo3:
      "In case you forgot to use the trip logger during your trip, you can also enter a trip afterwards by using your vehicles current kilometerage and trip length.",
    reports: "Reporting",
    reportInfo1: "Download comprehensive timesheets and trip logs in Excel or CSV format.",
    reportInfo2: "Set a date interval or quickly select one of the predefined intervals.",
    pricing: "Pricing",
    pricingInfo:
      "Using the Pulikka app will not break the bank: affordable prices that can even be lowered by inviting new users to the application!",
    threeMonths: "3 months",
    twelveMonths: "12 months",
    serviceUnavailable: "Service is not yet available! Check back later.",
    month: "month",
    threeMonthPrice: "9.00 €",
    threeMonthMonthlyPrice: "3.00 €/month",
    twelveMonthPrice: "29.90 €",
    twelveMonthMonthlyPrice: "2.49 €/month",
    acceptCookies: "I accept",
    siteUsesCookies: "This site uses cookies to enable the correct operation. Read more from our ",
    here: "privacy statement",
    only: "only",
  },
  fi: {
    signInWithGoogle: "Kirjaudu Google-tilillä",
    serverNotResponding: "Palvelin ei vastaa. Ole hyvä ja yritä myöhemmin uudelleen.",
    errorSendingPasswordResetEmail:
      "Sähköpostin lähettäminen salasanan vaihtamiseksi ei onnistunut. Yritä myöhemmin uudelleen.",
    linkSentToEmail: "Sähköpostiisi on lähetetty linkki salasanan vaihtamiseksi",
    requestPasswordResetEmail: "Tilaa salasanan palautuslinkki sähköpostiisi",
    email: "Sähköposti",
    send: "Send",
    password: "Salasana",
    signIn: "Kirjaudu",
    signUp: "Rekisteröidy",
    forgotPassword: "Unohditko salasanasi? Palauta salasana täältä",
    accountCreationFailed: "Tilin luonti ei onnistunut",
    emailAlreadyInUse: "Sähköpostiosoite on jo käytössä",
    invalidEmail: "Sähköpostiosoite ei kelpaa",
    passwordTooWeak: "Salasana liian heikko. Salasanan tulee olla vähintään 6 merkkiä.",
    emailPasswordAccountsAreNotEnabled:
      "Sähköpostilla ja salasanalla rekisteröitävät tilit eivät ole käytössä",
    appTitle: "Helppokäyttöinen työajanseuranta ja ajopäiväkirja",
    infoText1: "Rekisteröidy ja kokeile sovellusta 30 päivää ilmaiseksi",
    infoText2: "Vain 29,90 €/vuosi kokeilun jälkeen!",
    startFreeTrial: "Aloita ilmainen kokeilu",
    timesheets: "Työajanseuranta",
    timesheetInfo1: "Käytä haluamallasi laitteella.",
    timesheetInfo2: "Merkkaa työaikasi nopeasti ennalta määritettyjen pikavalintojen avulla.",
    timesheetInfo3: "Lisää päivärahat ja tauot.",
    timesheetInfo4:
      "Seuraa työaikaa tarkasti määrittämällä työaikasi yhdellä napinpainalluksella työpäiväsi alkeassa ja loppuessa",
    triplogs: "Ajopäiväkirja",
    triplogInfo1: "Pidä kirjaa työajoistasi - nopea ja helppo mittarilukeman asettaminen.",
    tripLogInfo2:
      "Käytä ohjelmaa matkasi alussa ja lopussa kirjaamalla nopeasti ajoneuvosi mittarilukema.",
    tripLogInfo3:
      "Jos unohdit käyttää ajopäiväkirjaa matkan aikana, voit lisätä matkoja myös jälkikäteen.",
    reports: "Raportit",
    reportInfo1:
      "Lataa kattavat työaikakirjaukset tai ajopäiväkirja kätevänä Excel- tai CSV raporttina.",
    reportInfo2: "Käytä pikavalintoja tai aseta aikaväli haluamallasi tavalla.",
    pricing: "Hinnasto",
    pricingInfo:
      "Pulikan käyttäminen ei tee lovea tuloihisi: edulliset hinnat mistä on lisäksi mahdollista saada pysyvää alennusta kutsumalla sovellukseen lisää käyttäjiä!",
    threeMonths: "3 kuukautta",
    twelveMonths: "12 kuukautta",
    serviceUnavailable: "Palvelu ei ole vielä käytössä! Palaa myöhemmin.",
    month: "kk",
    threeMonthPrice: "9,00 €",
    threeMonthMonthlyPrice: "3,00 €/kk",
    twelveMonthPrice: "29,90 €",
    twelveMonthMonthlyPrice: "2,49 €/kk",
    acceptCookies: "Hyväksyn",
    siteUsesCookies: "Sivusto käyttää evästeitä toiminnallisuuden takaamiseksi. Lue lisää ",
    here: "rekisteri- ja tietosuojaselosteesta",
    only: "vain",
  },
});

export default strings;
