import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    signInWithGoogle: "Sign in with Google",
    signInWithFacebook: "Sign in with Facebook",
    serverNotResponding: "Server is not responding. Please try again later.",
    errorSendingPasswordResetEmail:
      "Error while sending email for password reset. Please try again later.",
    linkSentToEmail: "A link for resetting your password has been sent to your email",
    requestPasswordResetEmail: "Request a link to reset your password",
    email: "Email",
    send: "Send",
    password: "Password",
    signIn: "Sign in",
    signUp: "Sign up",
    forgotPassword: "Forgot password? Request reset here",
    confirmEmail: "Confirm your email by clicking on the link sent to your email",
    accountCreationFailed: "Account creation failed",
    emailAlreadyInUse: "Email is already in use",
    invalidEmail: "Invalid email address",
    passwordTooWeak: "Password is too weak. Must be atleast 6 characters.",
    emailPasswordAccountsAreNotEnabled: "Email & Password accounts are not enabled",
    appTitle: "Easy to use timesheets and trip logging",
    infoText1: "Register for a free 30 day trial",
    startFreeTrial: "Start free trial",
    timesheets: "Timesheets",
    timesheetInfo1:
      "Keep track of your work for multiple project flexibly on any device with a browser.",
    timesheetInfo2: "Use quick selection times for inputting frequently used working times",
    timesheetInfo3: "Add daily allowance.",
    timesheetInfo4: "Add lunch breaks and other breaks.",
    timesheetInfo5: "Start and end your working day with a single button press.",
    triplogs: "Trip logs",
    triplogInfo1:
      "Keep track of your trips - quick and easy way to input your vehicle's kilometerage.",
    tripLogInfo2: "Add trips quickly by inputting kilometerage at the start and end of your trip.",
    tripLogInfo3:
      "In case you forgot to use the trip logger during your trip, you can also enter a trip afterwards by using your vehicles current kilometerage and trip length.",
    reports: "Reporting",
    reportInfo1: "Download reports in Excel or CSV format.",
    reportInfo2: "Set a date interval or quickly select one of the predefined intervals.",
    pricing: "Pricing",
    pricingInfo:
      "Using the Pulikka app will not break the bank: affordable prices that can even be lowered by inviting new users to the application!",
    threeMonths: "3 months",
    twelveMonths: "12 months",
    priceIncludesVAT: "Price includes 24% VAT",
    allPricesInclude: "All prices include full access to",
    toTimesheets: "timesheets",
    toTripLogging: "trip logging",
    toReports: "extensive timesheet reports and trip log reports",
    serviceUnavailable: "Service is not yet available! Check back later.",
    month: "month",
    threeMonthPrice: "7.50 €",
    twelveMonthPrice: "24.90 €",
  },
  fi: {
    signInWithGoogle: "Kirjaudu Google-tilillä",
    signInWithFacebook: "Kirjaudu Facebook-tilillä",
    serverNotResponding: "Palvelin ei vastaa. Ole hyvä ja yritä myöhemmin uudelleen.",
    errorSendingPasswordResetEmail:
      "Sähköpostin lähettäminen salasanan vaihtamiseksi ei onnistunut. Yritä myöhemmin uudelleen.",
    linkSentToEmail: "Sähköpostiisi on lähetetty linkki salasanan vaihtamiseksi",
    requestPasswordResetEmail: "Tilaa salasanan palautuslinkki sähköpostiisi",
    email: "Sähköposti",
    send: "Send",
    password: "Salasana",
    signIn: "Kirjaudu",
    signUp: "Rekisteröidy",
    forgotPassword: "Unohditko salasanasi? Palauta salasana täältä",
    confirmEmail: "Vahvista sähköpostiosoitteesi klikkaamalla sinne lähetettyä linkkiä",
    accountCreationFailed: "Tilin luonti ei onnistunut",
    emailAlreadyInUse: "Sähköpostiosoite on jo käytössä",
    invalidEmail: "Sähköpostiosoite ei kelpaa",
    passwordTooWeak: "Salasana liian heikko. Salasanan tulee olla vähintään 6 merkkiä.",
    emailPasswordAccountsAreNotEnabled:
      "Sähköpostilla ja salasanalla rekisteröitävät tilit eivät ole käytössä",
    appTitle: "Helppokäyttöinen työajanseuranta ja ajopäiväkirja",
    infoText1: "Rekisteröidy ja kokeile sovellusta 30 päivää ilmaiseksi",
    startFreeTrial: "Aloita ilmainen kokeilu",
    timesheets: "Työajanseuranta",
    timesheetInfo1: "Merkkaa työaikasi haluamallasi laitteella.",
    timesheetInfo2: "Merkkaa työaikasi nopeasti ennalta määritettyjen työaikojen avulla.",
    timesheetInfo3: "Lisää päivärahat.",
    timesheetInfo4: "Lisää luonastauot ja muut tauot.",
    timesheetInfo5: "Aloita ja lopeta työpäiväsi yhdellä napinpainalluksella.",
    triplogs: "Ajopäiväkirja",
    triplogInfo1: "Pidä kirjaa työajoistasi - nopea ja helppo mittarilukeman asettaminen.",
    tripLogInfo2:
      "Käytä ohjelmaa matkasi alussa ja lopussa kirjaamalla nopeasti ajoneuvosi mittarilukema.",
    tripLogInfo3:
      "Jos unohdit käyttää ajopäiväkirjaa matkan aikana, voit lisätä matkoja myös jälkikäteen.",
    reports: "Raportit",
    reportInfo1: "Lataa raportit Excel- tai CSV-formaatissa.",
    reportInfo2: "Aseta aikaväli tai käytä pikavalintoja.",
    pricing: "Hinnasto",
    pricingInfo:
      "Pulikan käyttäminen ei tee lovea tuloihisi: edulliset hinnat joista on lisäksi mahdollista saada pysyvää alennusta kutsumalla sovellukseen lisää käyttäjiä!",
    threeMonths: "3 kuukautta",
    twelveMonths: "12 kuukautta",
    priceIncludesVAT: "Hinta sisältää 24% alv.",
    allPricesInclude: "Kaikki hinnat sisältävät täyden käyttöoikeuden",
    toTimesheets: "työajanseurantaan",
    toTripLogging: "ajopäiväkirjan pitämiseen",
    toReports: "kattavien työaikaraporttien ja ajopäiväkirjojen lataamiseen",
    serviceUnavailable: "Palvelu ei ole vielä käytössä! Palaa myöhemmin.",
    month: "kk",
    threeMonthPrice: "7,50 €",
    twelveMonthPrice: "24,90 €",
  },
});

export default strings;
