import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    projectCannotBeEmpty: "Project name cannot be empty",
    projectMustBeSelected: "Select a project",
    addingProjectFailed: "Adding project failed. Please try again later",
    addProject: "Add project",
    projectName: "Project name",
    hourlyRate: "Hourly rate",
    add: "Add",
    close: "Close",
    timeAlreadyAdded: "Work time already added",
    addingWorktimeFailed: "Adding work time failed. Please try again later.",
    addWorktime: "Add working time",
    start: "Starting",
    end: "Ending",
    dailyAllowance: "Daily allowance",
    removingProjectFailed: "Removing project failed. Please try again later.",
    project: "Project",
    projects: "Projects",
    noAddedProjects: "No added projects",
    quickSelect: "Quick selection",
    noQuickSelections: "No quick selections. Add in your profile page.",
    lunchBreakDurationMustBeInt: "Lunch duration must be an integer",
    breakDurationMustBeInt: "Breaks duration must be an integer",
    lunch: "Lunch",
    breaks: "Breaks",
    startNow: "Start now",
    started: "Started",
    endNow: "End Now",
    ended: "Ended",
    worktimeSaved: "Work time saved",
    selectedProjectNotFound: "Selected project not found from the database",
    savingWorktimeFailed: "Saving work time failed. Please try again later.",
    reset: "Reset",
    save: "Save",
    removingWorktimeFailed: "Removing working time failed. Please try again later.",
    quickSelection: "Quick work time selections",
    startingDate: "Starting date",
    time: "Time",
    endingDate: "Ending date",
    duration: "Duration",
    accountNoLongerActive:
      "Your account is no longer active. Purchase again to keep using the application.",
    accountActive: "Your account is active until",
    until: "",
    accountExpired: "Your account has expired on",
    deleteMyAccount: "Delete account",
    deleteNote:
      "Deleting your user account will remove all your data from the application. Are you sure you want to delete your account?",
    delete: "Delete my user account",
    password: "Password",
    checkPassword: "Invalid password",
    accountRemoved: "Your account has been removed",
    thanksForTheFeedback: "Thank you for your feedback!",
    thanksForTheReview: "Thank you for reviewing the application!",
    errorSendingFeedback: "Sending feedback failed. Please try again later.",
    errorSendingReview: "Sending review failed. Please try again later.",
    sendFeedback: "Send feedback",
    chooseTopicForFeedback: "Choose a topic for your feedback",
    feedbackCannotBeEmpty: "Feedback cannot be empty",
    suggestions: "Suggestions",
    complaints: "Complaints",
    other: "Other",
    send: "Send",
    feedback: "Feedback",
    updateReview: "Update your review",
    reviewTheApplication: "Review the application - receive 20% discount on your next purchase!",
    invalidRating: "Invalid rating",
    reviewCannotBeEmpty: "Review cannot be empty",
    alias: "Alias",
    yourRating: "Your rating",
    review: "Review",
    update: "Update",
    subject: "Subject",
    inviteUsers: "Invite users",
    inviteInfo:
      "Send this link to a friend. You will receive a permanent 1 € discount on your annual price every time a user you invited makes their first purchase in the application. The invited user receives a 20% discount on their first purchase as well.",
    annualPriceInfo: "Annual price minimum 9.90 €",
    linkCopied: "Link copied to clipboard",
  },
  fi: {
    projectCannotBeEmpty: "Projektin nimi on täytettävä",
    projectMustBeSelected: "Valitse projekti",
    addingProjectFailed: "Projektin lisääminen ei onnistunut. Yritä myöhemmin uudelleen.",
    addProject: "Lisää projekti",
    projectName: "Projektin nimi",
    hourlyRate: "Tuntilaskutus",
    add: "Lisää",
    close: "Sulje",
    timeAlreadyAdded: "Aika on jo lisätty",
    addingWorktimeFailed: "Työajan lisääminen ei onnistunut. Yritä myöhemmin uudelleen.",
    addWorktime: "Lisää työaika",
    start: "Aloitus",
    end: "Lopetus",
    dailyAllowance: "Päiväraha",
    removingProjectFailed: "Projektin poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    project: "Projekti",
    projects: "Projektit",
    noAddedProjects: "Ei lisättyjä projekteja",
    quickSelect: "Pikavalinta",
    noQuickSelections: "Ei pikavalintoja. Lisää profiili-sivulla.",
    lunchBreakDurationMustBeInt: "Lounaan kesto tulee olla kokonaisluku",
    breakDurationMustBeInt: "Taukojen kesto tulee olla kokonaisluku",
    lunch: "Lounas",
    breaks: "Muut tauot",
    startNow: "Aloita nyt",
    started: "Aloitettu",
    endNow: "Lopeta nyt",
    ended: "Lopetettu",
    worktimeSaved: "Työaika tallennettu",
    selectedProjectNotFound: "Valitsemaasi projektia ei löytynyt tietokannasta.",
    savingWorktimeFailed: "Virhe tallennettaessa työaikaa. Yritä myöhemmin uudelleen.",
    reset: "Nollaa",
    save: "Tallenna",
    removingWorktimeFailed:
      "T(e) => setVehicle(e.target.value)yöajan poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    quickSelection: "Työaikojen pikavalinnat",
    startingDate: "Aloitus pvm",
    time: "Aika",
    endingDate: "Lopetus pvm",
    duration: "Kesto",
    accountNoLongerActive:
      "Tilisi ei ole enää aktiivinen. Osta sovelluksen käyttöoikeus jatkaaksesi käyttöä.",
    accountActive: "Tilisi on aktiivinen",
    until: " asti",
    accountExpired: "Tilisi käyttöoikeus on päättynyt",
    deleteMyAccount: "Poista käyttäjätili",
    deleteNote:
      "Poistamalla tilisi kaikki sovelluksessa olevat tietosi poistetaan. Oletko varma, että halua poistaa tilisi?",
    delete: "Poista käyttäjätilini",
    password: "Salasana",
    checkPassword: "Tarkista salasana",
    accountRemoved: "Käyttäjätilisi on poistettu",
    thanksForTheFeedback: "Kiitos palautteesta!",
    thanksForTheReview: "Kiitos arvostelusta",
    errorSendingFeedback:
      "Palautteen antaminen ei onnistunut. Ole hyvä ja yritä myöhemmin uudelleen.",
    errorSendingReview:
      "Arvostelun antaminen ei onnistunut. Ole hyvä ja yritä myöhemmin uudelleen.",
    sendFeedback: "Anna palautetta",
    chooseTopicForFeedback: "Valitse palautteen aihe",
    feedbackCannotBeEmpty: "Palaute ei voi olla tyhjä",
    suggestions: "Ehdotukset",
    complaints: "Vikailmoitukset",
    other: "Muu",
    send: "Lähetä",
    feedback: "Palaute",
    updateReview: "Päivitä arvostelusi",
    reviewTheApplication: "Arvostele sovellus - saat 20% alennuksen seuraavasta ostoksestasi!",
    invalidRating: "Virheellinen arvosana",
    reviewCannotBeEmpty: "Arvostelu ei voi olla tyhjä",
    alias: "Nimimerkki",
    yourRating: "Mielipiteesi",
    review: "Arvostelu",
    update: "Päivitä",
    subject: "Aihe",
    inviteUsers: "Kutsu käyttäjiä",
    inviteInfo:
      "Lähetä tämä linkki tuttavillesi. Saat pysyvän 1 € alennuksen vuosihintaasi jokaista kutsumaasi oston tehnyttä käyttäjää kohden! Kutsuttu käyttäjä saa 20% alennuksen ensimmäisestä ostoksestaan.",
    annualPriceInfo: "Vuosihinta alimmillaan 9,90 €",
    linkCopied: "Linkki kopioitu",
  },
});

export default strings;
