import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    projectMustBeSelected: "Select a project",
    dailyAllowance: "Daily allowance",
    project: "Project",
    projects: "Projects",
    quickSelect: "Quick selection",
    noQuickSelections: "No quick selections. Add in your profile page.",
    lunchBreakDurationMustBeInt: "Lunch duration must be an integer",
    breakDurationMustBeInt: "Breaks duration must be an integer",
    add: "Add",
    lunch: "Lunch",
    breaks: "Breaks",
    startNow: "Start now",
    started: "Start",
    endNow: "End Now",
    ended: "Ended",
    start: "Start",
    end: "End",
    worktimeSaved: "Working time saved",
    selectedProjectNotFound: "Selected project not found from the database",
    savingWorktimeFailed: "Saving work time failed. Please try again later.",
    reset: "Reset",
    save: "Save",
    removingWorktimeFailed: "Removing working time failed. Please try again later.",
    startingDate: "Starting date",
    time: "Time",
    endingDate: "Ending date",
    duration: "Duration",
    accountNoLongerActive:
      "Your account is no longer active. Purchase again to keep using the application.",
    summary: "Summary",
    workingTime: "Working time",
    errorLoadingLatestWorkdata: "Error while loading latest workdata. Please, try again later.",
    latestWorkingTime: "Latest working time",
  },
  fi: {
    projectMustBeSelected: "Valitse projekti",
    dailyAllowance: "Päiväraha",
    project: "Projekti",
    projects: "Projektit",
    quickSelect: "Pikavalinta",
    noQuickSelections: "Ei pikavalintoja. Lisää profiili-sivulla.",
    lunchBreakDurationMustBeInt: "Lounaan kesto tulee olla kokonaisluku",
    breakDurationMustBeInt: "Taukojen kesto tulee olla kokonaisluku",
    add: "Lisää",
    lunch: "Lounas",
    breaks: "Muut tauot",
    startNow: "Aloita nyt",
    started: "Alku",
    endNow: "Lopeta nyt",
    ended: "Loppu",
    start: "Aloitus",
    end: "Lopetus",
    worktimeSaved: "Työaika tallennettu",
    selectedProjectNotFound: "Valitsemaasi projektia ei löytynyt tietokannasta.",
    savingWorktimeFailed: "Virhe tallennettaessa työaikaa. Yritä myöhemmin uudelleen.",
    reset: "Nollaa",
    save: "Tallenna",
    removingWorktimeFailed: "Työajan poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    startingDate: "Aloitus päivämäärä",
    time: "Aika",
    endingDate: "Lopetus päivämäärä",
    duration: "Kesto",
    accountNoLongerActive:
      "Tilisi ei ole enää aktiivinen. Osta sovelluksen käyttöoikeus jatkaaksesi käyttöä.",
    summary: "Yhteenveto",
    workingTime: "Työaika",
    errorLoadingLatestWorkdata:
      "Virhe ladattaessa viimeisintä työaikaa. Ole hyvä ja yritä myöhemmin uudelleen.",
    latestWorkingTime: "Viimeisin työaika",
  },
});

export default strings;
