import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    projectMustBeSelected: "Select a project",
    dailyAllowance: "Daily allowance",
    project: "Project",
    projects: "Projects",
    quickSelect: "Quick selection",
    noQuickSelections: "No quick selections. Add in your profile page.",
    lunchBreakDurationMustBeInt: "Lunch duration must be an integer",
    breakDurationMustBeInt: "Breaks duration must be an integer",
    lunch: "Lunch",
    breaks: "Breaks",
    startNow: "Start now",
    started: "Started",
    endNow: "End Now",
    ended: "Ended",
    worktimeSaved: "Working time saved",
    selectedProjectNotFound: "Selected project not found from the database",
    savingWorktimeFailed: "Saving work time failed. Please try again later.",
    reset: "Reset",
    save: "Save",
    removingWorktimeFailed: "Removing working time failed. Please try again later.",
    startingDate: "Starting date",
    time: "Time",
    endingDate: "Ending date",
    duration: "Duration",
    accountNoLongerActive:
      "Your account is no longer active. Purchase again to keep using the application.",
  },
  fi: {
    projectMustBeSelected: "Valitse projekti",
    dailyAllowance: "Päiväraha",
    project: "Projekti",
    projects: "Projektit",
    quickSelect: "Pikavalinta",
    noQuickSelections: "Ei pikavalintoja. Lisää profiili-sivulla.",
    lunchBreakDurationMustBeInt: "Lounaan kesto tulee olla kokonaisluku",
    breakDurationMustBeInt: "Taukojen kesto tulee olla kokonaisluku",
    lunch: "Lounas",
    breaks: "Muut tauot",
    startNow: "Aloita nyt",
    started: "Aloitettu",
    endNow: "Lopeta nyt",
    ended: "Lopetettu",
    worktimeSaved: "Työaika tallennettu",
    selectedProjectNotFound: "Valitsemaasi projektia ei löytynyt tietokannasta.",
    savingWorktimeFailed: "Virhe tallennettaessa työaikaa. Yritä myöhemmin uudelleen.",
    reset: "Nollaa",
    save: "Tallenna",
    removingWorktimeFailed: "Työajan poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    startingDate: "Aloitus pvm",
    time: "Aika",
    endingDate: "Lopetus pvm",
    duration: "Kesto",
    accountNoLongerActive:
      "Tilisi ei ole enää aktiivinen. Osta sovelluksen käyttöoikeus jatkaaksesi käyttöä.",
  },
});

export default strings;
