import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    projectCannotBeEmpty: "Project name cannot be empty",
    projectMustBeSelected: "Select a project",
    addingProjectFailed: "Adding project failed. Please try again later",
    addProject: "Add project",
    projectName: "Project name",
    hourlyRate: "Hourly rate",
    add: "Add",
    close: "Close",
    timeAlreadyAdded: "Work time already added",
    addingWorktimeFailed: "Adding work time failed. Please try again later.",
    start: "Starting",
    end: "Ending",
    dailyAllowance: "Daily allowance",
    removingProjectFailed: "Removing project failed. Please try again later.",
    project: "Project",
    projects: "Projects",
    noAddedProjects: "No added projects",
    quickSelect: "Quick selection",
    noQuickSelections: "No quick selections. Add in your profile page.",
    lunchBreakDurationMustBeInt: "Lunch duration must be an integer",
    breakDurationMustBeInt: "Breaks duration must be an integer",
    lunch: "Lunch",
    breaks: "Breaks",
    startNow: "Start now",
    started: "Started",
    endNow: "End Now",
    ended: "Ended",
    worktimeSaved: "Working time saved",
    selectedProjectNotFound: "Selected project not found from the database",
    savingWorktimeFailed: "Saving work time failed. Please try again later.",
    reset: "Reset",
    save: "Save",
    removingWorktimeFailed: "Removing working time failed. Please try again later.",
    quickSelection: "Quick work time selections",
    startingDate: "Starting date",
    time: "Time",
    endingDate: "Ending date",
    duration: "Duration",
    accountNoLongerActive:
      "Your account is no longer active. Purchase again to keep using the application.",
  },
  fi: {
    projectCannotBeEmpty: "Projektin nimi on täytettävä",
    projectMustBeSelected: "Valitse projekti",
    addingProjectFailed: "Projektin lisääminen ei onnistunut. Yritä myöhemmin uudelleen.",
    addProject: "Lisää projekti",
    projectName: "Projektin nimi",
    hourlyRate: "Tuntilaskutus",
    add: "Lisää",
    close: "Sulje",
    timeAlreadyAdded: "Aika on jo lisätty",
    addingWorktimeFailed: "Työajan lisääminen ei onnistunut. Yritä myöhemmin uudelleen.",
    start: "Aloitus",
    end: "Lopetus",
    dailyAllowance: "Päiväraha",
    removingProjectFailed: "Projektin poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    project: "Projekti",
    projects: "Projektit",
    noAddedProjects: "Ei lisättyjä projekteja",
    quickSelect: "Pikavalinta",
    noQuickSelections: "Ei pikavalintoja. Lisää profiili-sivulla.",
    lunchBreakDurationMustBeInt: "Lounaan kesto tulee olla kokonaisluku",
    breakDurationMustBeInt: "Taukojen kesto tulee olla kokonaisluku",
    lunch: "Lounas",
    breaks: "Muut tauot",
    startNow: "Aloita nyt",
    started: "Aloitettu",
    endNow: "Lopeta nyt",
    ended: "Lopetettu",
    worktimeSaved: "Työaika tallennettu",
    selectedProjectNotFound: "Valitsemaasi projektia ei löytynyt tietokannasta.",
    savingWorktimeFailed: "Virhe tallennettaessa työaikaa. Yritä myöhemmin uudelleen.",
    reset: "Nollaa",
    save: "Tallenna",
    removingWorktimeFailed:
      "T(e) => setVehicle(e.target.value)yöajan poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    quickSelection: "Työaikojen pikavalinnat",
    startingDate: "Aloitus pvm",
    time: "Aika",
    endingDate: "Lopetus pvm",
    duration: "Kesto",
    accountNoLongerActive:
      "Tilisi ei ole enää aktiivinen. Osta sovelluksen käyttöoikeus jatkaaksesi käyttöä.",
  },
});

export default strings;
