import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    vehicleCannotBeEmpty: "Vehicle cannot be empty",
    addingVehicleFailed: "Adding vehicle failed. Please try again later",
    addVehicle: "Add vehicle",
    add: "Add",
    confirmCancel: "Confirm cancel",
    cancelInfo: "Cancelled trip start or end cannot be recovered",
    close: "Close",
    confirm: "Confirm",
    numberMustBeAnInteger: "Number must be an integer",
    give: "Give",
    number: "number",
    numbers: "numbers",
    kilometerage: "Kilometerage",
    summary: "Summary",
    vehicle: "Vehicle",
    start: "Start",
    kilometerageAtStart: "Kilometerage at start",
    kilometerageAtEnd: "Kilometerage at end",
    end: "End",
    tripDistance: "Trip length (km)",
    removingVehicleFailed: "Removing vehicle failed. Please try again later.",
    cancel: "Cancel",
    save: "Save",
    addTripManually: "Add forgotten trip",
    locationAtStart: "Starting address",
    locationAtEnd: "Ending address",
    kilometerageNow: "Kilometerage now",
    tripStart: "Trip start",
    tripEnd: "Trip end",
    manualTripHelpText: "Remember to use the description!",
    invalidManualValues: "Invalid value for kilometerage and/or trip distance",
    errorSavingTrip: "Saving your trip failed. Please try again later.",
    tripSavedSuccessfully: "Trip saved successfully",
    accountNoLongerActive:
      "Your account is no longer active. Purchase again to keep using the application.",
  },
  fi: {
    vehicleCannotBeEmpty: "Ajoneuvo ei voi olla tyhjä",
    addingVehicleFailed: "Ajoneuvon lisääminen epäonnistui. Yritä myöhemmin uudelleen",
    addVehicle: "Lisää ajoneuvo",
    add: "Lisää",
    confirmCancel: "Vahvista peruutus",
    cancelInfo: "Peruutettua matkan aloitusta tai lopetusta ei voi palauttaa",
    close: "Sulje",
    confirm: "Vahvista",
    numberMustBeAnInteger: "Numeron täytyy olla kokonaisluku",
    give: "Anna",
    number: "luku",
    numbers: "lukua",
    summary: "Yhteenveto",
    vehicle: "Ajoneuvo",
    kilometerage: "Mittarilukema",
    start: "Aloita",
    kilometerageAtStart: "Mittarilukema alussa",
    kilometerageAtEnd: "Mittarilukema lopussa",
    end: "Lopeta",
    tripDistance: "Matkan pituus (km)",
    removingVehicleFailed: "Ajoneuvon poistaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    cancel: "Peruuta",
    save: "Tallenna",
    addTripManually: "Lisää unohtunut matka",
    locationAtStart: "Osoite alussa",
    locationAtEnd: "Osoite lopussa",
    kilometerageNow: "Mittarilukema nyt",
    tripStart: "Matkan alku",
    tripEnd: "Matkan lopetus",
    manualTripHelpText: "Muista lisätä kuvaus!",
    invalidManualValues: "Tarkasta mittarilukema ja/tai matkan pituus",
    errorSavingTrip: "Matkan tallentaminen ei onnistunut. Yritä myöhemmin uudelleen.",
    tripSavedSuccessfully: "Matka tallennettu",
    accountNoLongerActive:
      "Tilisi ei ole enää aktiivinen. Osta sovelluksen käyttöoikeus jatkaaksesi käyttöä.",
  },
});

export default strings;
